### ISSUE TITLE
Exception in callback Task.__wakeup(<Future finished result=None>)

### ISSUE THREAD

**Issue by grcdeepak1** [erdewit/nest_asyncio#29] opened 2020-06-09 20:42 UTC
Exception in callback Task.__wakeup(<Future finished result=None>)
handle: <Handle Task.__wakeup(<Future finished result=None>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nest_asyncio.py", line 150, in run
    ctx.run(self._callback, *self._args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 329, in __wakeup
    self.__step()
  File "/usr/local/lib/python3.7/site-packages/nest_asyncio.py", line 108, in step
    step_orig(task, exc)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 313, in __step
    _leave_task(self._loop, self)
  File "/usr/local/lib/python3.7/site-packages/nest_asyncio.py", line 122, in leave_task
    del curr_tasks[loop]
KeyError: <_UnixSelectorEventLoop running=True closed=False debug=False>

**Comment by esbenr** [comment] 2020-06-29 20:06
I have the same problem. Any Ideas how to fix this? I would like to contribute.

**Comment by erdewit** [comment] 2020-07-16 13:16
Duplicate of #26

**Closed by erdewit** 2020-07-16 13:16 UTC
