### ISSUE TITLE
Python 3.8.2 breaks nest-asyncio

### ISSUE THREAD

**Issue by crusaderky** [erdewit/nest_asyncio#20] opened 2020-03-03 13:32 UTC
This trivial demo works with CPython 3.8.1 and breaks with 3.8.2:

```python
import asyncio
import nest_asyncio
nest_asyncio.apply()


async def f():
    print("OK")


async def g():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(f())

if __name__ == "__main__":
    asyncio.run(g())
```

#### Works
- Linux x64, anaconda, nest_asyncio 1.2.2
- python=3.8.1=h357f687_2 (conda-forge)

Output: OK

#### Broken
- Linux x64, anaconda, nest_asyncio 1.2.2
- python=3.8.2=h9d8adfe_1_cpython (conda-forge)

Output: RuntimeError: This event loop is already running

**Comment by crusaderky** [comment] 2020-03-03 14:25
I can see a problem in travis. As of the latest build on Jan 28, all tests are failing in 'nightly' but the tick is green: https://travis-ci.org/erdewit/nest_asyncio/jobs/642857718?utm_medium=notification&utm_source=github_status

**Comment by erdewit** [comment] 2020-03-05 17:46
Thanks for the headsup. It is caused by the addition of [this line](https://github.com/python/cpython/blob/efc28bbbeee07867669dfbf49385d6a2147fe631/Lib/asyncio/base_events.py#L618) in asyncio.

I'll have to figure a way around it.

**Comment by erdewit** [comment] 2020-03-10 09:28
This has been fixed in v1.3 by reimplementing ``run_until_complete``.

**Closed by erdewit** 2020-03-10 09:28 UTC

**Comment by gordonwatts** [comment] 2020-03-10 16:26
Thanks!!

**Comment by gordonwatts** [comment] 2020-03-11 03:44
I'm getting lots of errors in my tests with 1.3.0. Sadly, my unit tests aren't all that "unit"... but I was able to create a small test case:

```

def test_1():
    async def doit():
        raise BaseException("boom")

    try:
        import nest_asyncio
        nest_asyncio.apply()
        loop1 = asyncio.get_event_loop()
        loop1.run_until_complete(doit())
    except:
        pass

@pytest.mark.asyncio
async def test_3():
    pass

def test_5():
    async def doit():
        return

    import nest_asyncio
    nest_asyncio.apply()
    loop1 = asyncio.get_event_loop()
    loop1.run_until_complete(doit())
```

When I run this, I get the following output from pytest:

```
============================= test session starts =============================
platform win32 -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: i:\gwatts\Code\irishep\func_adl, inifile: pytest.ini
plugins: asyncio-0.10.0, cov-2.8.1
collected 3 items

tests\test_ObjectStream.py ..Task exception was never retrieved
future: <Task finished coro=<test_1.<locals>.doit() done, defined at I:\gwatts\Code\irishep\func_adl\tests\test_ObjectStream.py:95> exception=BaseException('boom')>
Traceback (most recent call last):
  File "I:\gwatts\Code\irishep\func_adl\tests\test_ObjectStream.py", line 102, in test_1
    loop1.run_until_complete(doit())
  File "i:\gwatts\Code\irishep\func_adl\.venv\3.7\lib\site-packages\nest_asyncio.py", line 54, in run_until_complete
    self._run_once()
  File "i:\gwatts\Code\irishep\func_adl\.venv\3.7\lib\site-packages\nest_asyncio.py", line 85, in _run_once
    handle._run()
  File "i:\gwatts\Code\irishep\func_adl\.venv\3.7\lib\site-packages\nest_asyncio.py", line 144, in run
    ctx.run(self._callback, *self._args)
  File "i:\gwatts\Code\irishep\func_adl\.venv\3.7\lib\site-packages\nest_asyncio.py", line 102, in step
    step_orig(task, exc)
  File "c:\Users\gordo\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 249, in __step
    result = coro.send(None)
  File "I:\gwatts\Code\irishep\func_adl\tests\test_ObjectStream.py", line 96, in doit
    raise BaseException("boom")
BaseException: boom
F                                           [100%]

================================== FAILURES ===================================
___________________________________ test_5 ____________________________________

    def test_5():
        async def doit():
            return
    
        import nest_asyncio
        nest_asyncio.apply()
        loop1 = asyncio.get_event_loop()
>       loop1.run_until_complete(doit())

tests\test_ObjectStream.py:117: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.venv\3.7\lib\site-packages\nest_asyncio.py:48: in run_until_complete
    self._check_closed()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_WindowsSelectorEventLoop running=False closed=True debug=False>

    def _check_closed(self):
        if self._closed:
>           raise RuntimeError('Event loop is closed')
E           RuntimeError: Event loop is closed

c:\Users\gordo\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py:479: RuntimeError
- generated xml file: C:\Users\gordo\AppData\Local\Temp\tmp-8256cLGIMzAKOGXe.xml -
WARNING: Coverage disabled via --no-cov switch!
========================= 1 failed, 2 passed in 0.07s =========================
Error: Error: cannot open file:///i%3A/gwatts/Code/irishep/func_adl/c. Detail: Unable to read file 'i:\gwatts\Code\irishep\func_adl\c' (Error: Unable to resolve non-existing file 'i:\gwatts\Code\irishep\func_adl\c')
```

This output was on Windows. However, I first discovered this because all my CI's started failing on linux, macOS, and Windows together with this same error.

Am I abusing asyncio here (likely). Under 1.2.3 of nest_asyncio, btw, and python 3.7.6, there are no errors like this.

I've not tested in any other version of python yet.

**Comment by erdewit** [comment] 2020-03-11 11:50
Gordon, there are two different things going on here:

The first is raising a ``BaseException`` that is not caught. This happens without nest_asyncio as well. There's some special handling of BaseException in asyncio. Not sure why but could have to de with catching KeyboardInterupt. Raising ``Exception`` will be caught.

Second is that the ``pytest.mark.asyncio`` seems to close the current event loop. The intention probably being to create a fresh new loop for each test (for example using a fixture).

**Comment by gimperiale** [comment] 2020-03-11 12:07
Tested 1.3 vs Python 3.8.2; everything works for me.
@gordonwatts pytest-asyncio tampers with the asyncio event loop. I use it too but I was very careful not to mix it with nest-asyncio, uvloop, etc. 

Try adding to your conftest.py:

```python
@pytest.fixture(scope="session")
def event_loop():
    """Don't close event loop at the end of every function decorated by
    @pytest.mark.asyncio
    """
    loop = asyncio.new_event_loop()
    yield loop
    loop.close()
```

**Comment by gordonwatts** [comment] 2020-03-11 14:53
Thanks for the fast response!

I definitely using both async and non-async tests - this library has to supply both interfaces (hence the need for `nest_asyncio`). I don't know of a way to carefully avoid mixing the two.

As far as tampering with the asyncio event loop - that was happening with `nest_asyncio` version 1.2.3 - but something has changed with the handling in 1.30 which makes it fatal.

I'll try adding the fixture.

**Comment by nabobalis** [comment] 2020-04-28 13:19
Just wanted to say I had this issue as well on python 3.8.2 and adding this to my conftest.py worked:

```
import pytest
import asyncio
import nest_asyncio


@pytest.fixture(scope="session")
def event_loop():
    """
    Don't close event loop at the end of every function decorated by
    @pytest.mark.asyncio
    """
    loop = asyncio.new_event_loop()
    nest_asyncio.apply()
    yield loop
    loop.close()
```
